name: Release
run-name: Release ${{ github.ref_name }}

on:
  release:
    types: [ created ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'
          java-package: jdk
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          ARTIFACT_REPOSITORY_USERNAME: ${{ github.actor }}
          ARTIFACT_REPOSITORY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
